<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '10',
    'typeid' => '0',
    'title' => '00020002',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '00020002000200020002',
    'posids' => '0',
    'url' => 'http://localhost:9999/bootstrap_boke/index.php?m=content&c=index&a=show&catid=10&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1511180470',
    'updatetime' => '1511180534',
    'hitsid' => 'c-1-4',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '10',
    'typeid' => '0',
    'title' => '混合混合或或或或或',
    'style' => '',
    'thumb' => '',
    'keywords' => '混合混合或或或或或',
    'description' => 'hhhhhhhhhhhhh',
    'posids' => '0',
    'url' => 'http://localhost:9999/bootstrap_boke/index.php?m=content&c=index&a=show&catid=10&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1511180754',
    'updatetime' => '1511180865',
    'hitsid' => 'c-1-9',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '10',
    'typeid' => '0',
    'title' => '混合混合或或或或或或或或或或',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '混合混合或或或或或或或或或或或或或',
    'posids' => '0',
    'url' => 'http://localhost:9999/bootstrap_boke/index.php?m=content&c=index&a=show&catid=10&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1511180769',
    'updatetime' => '1511180891',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '10',
    'typeid' => '0',
    'title' => '66',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '66',
    'posids' => '0',
    'url' => 'http://localhost:9999/bootstrap_boke/index.php?m=content&c=index&a=show&catid=10&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1511180894',
    'updatetime' => '1511180897',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '10',
    'typeid' => '0',
    'title' => '0002',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '0002000200020002',
    'posids' => '0',
    'url' => 'http://localhost:9999/bootstrap_boke/index.php?m=content&c=index&a=show&catid=10&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1511180452',
    'updatetime' => '1511180465',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '10',
    'typeid' => '0',
    'title' => '班vvvvvvvvvvvvvvvvvvvvvvv',
    'style' => '',
    'thumb' => '',
    'keywords' => '班vvvvvvvvvvvvvvvvvvvvvvv',
    'description' => '表表表vvvvvvvvvvvvvvvvv',
    'posids' => '0',
    'url' => 'http://localhost:9999/bootstrap_boke/index.php?m=content&c=index&a=show&catid=10&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1511180712',
    'updatetime' => '1511180723',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '10',
    'typeid' => '0',
    'title' => '少时诵诗书所所所所所所所所所所所所所所',
    'style' => '',
    'thumb' => '',
    'keywords' => '少时 诗书',
    'description' => '少时诵诗书所所所所所所所所所所所所所所所',
    'posids' => '0',
    'url' => 'http://localhost:9999/bootstrap_boke/index.php?m=content&c=index&a=show&catid=10&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1511180725',
    'updatetime' => '1511180731',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '10',
    'typeid' => '0',
    'title' => '少时诵诗书所所所所所所所所所所所所所所所所所所',
    'style' => '',
    'thumb' => '',
    'keywords' => '少时 诗书',
    'description' => '少时诵诗书所所所所所所所所所所',
    'posids' => '0',
    'url' => 'http://localhost:9999/bootstrap_boke/index.php?m=content&c=index&a=show&catid=10&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1511180733',
    'updatetime' => '1511180739',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '10',
    'typeid' => '0',
    'title' => '的点点滴滴多多多多多多多',
    'style' => '',
    'thumb' => '',
    'keywords' => '点点滴滴',
    'description' => '的点点滴滴多多多多多多多',
    'posids' => '0',
    'url' => 'http://localhost:9999/bootstrap_boke/index.php?m=content&c=index&a=show&catid=10&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1511180742',
    'updatetime' => '1511180752',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>